### ISSUE TITLE
Are you going to support Linux?

### ISSUE THREAD

**Issue by pplonski** [rnd-team-dev/plotoptix#1]
I've found your package and it looks amazing! Great job! :+1:  :1st_place_medal: Are you going to support Linux? Do you have a roadmap for package development?

**Comment by robertsulej** [comment]
Thanks Piotr!

Yes, Linux is in the plan. Package is still in its early stage, and the first priority was to make use of the RT Cores when running on the Turing architecture. This is done and the new release should be uploaded to PyPI in a day or two.

The roadmap is roughly outlined at the end of README. Linux is on the top. I think Ubuntu 18.04 will go first as it is the platform on Google Colab. It would be really interesting to try ray tracing running in the Colab notebook - they have Tesla T4 GPUs there.

**Comment by robertsulej** [comment]
Everything seems working. So far testing in Ubuntu. FFmpeg and pythonnet need to be installed in the system, if you'd like to try it now. I'll write installation instructions.

Before closing the issue and freezing new release I plan to add few more tests. This will take a day or two.

**Comment by robertsulej** [comment]
Ok, the new release with Linux support is uploaded to PyPI. Installation instructions are tested in Ubuntu 18.04 and CentOS 7. I close this issue. Feel free to open a new one if any troubles appear.
