### ISSUE TITLE
Set number of bounces

### ISSUE THREAD

**Issue by mworchel** [rnd-team-dev/plotoptix#19]
Hi,

is there a way to control the number of bounces used by the raytracer? The motivation is, that I would like to get a completely unshaded plot by setting ambient to `1.0` and bounces to 0 (so only direct hits count). 

Thanks in advance!

**Comment by mworchel** [comment]
Ah, I guess the `flat` material is what I was looking for. I overlooked it, sorry : )

**Comment by robertsulej** [comment]
Another option is to set `rt.set_uint("path_seg_range", 1, 1)`. This will take into account direct impact of lights in the scene.

**Comment by mworchel** [comment]
Awesome, thanks for the alternative way! Are these variables documented explicitly somewhere?

**Comment by robertsulej** [comment]
`path_seg_range` is only explained in examples.

There are many variables that can be modified with `set_int()`, `set_float()`, etc, which means they live on GPU. But they are related to various different configurations and algorithms end described there. Only `path_seg_range` did not find its place in dosc, I should fix that... and maybe add one more section with all these variables collected in one place.
