### ISSUE TITLE
works with cuda 10.1?

### ISSUE THREAD

**Issue by kittles** [rnd-team-dev/plotoptix#2]
im on ubuntu 16.01, i just installed cuda 10.1

after monkey patching import IntEnum as IntFlag, which was causing an import error, i get another error:

```
Traceback (most recent call last):
  File "/home/patrick/.local/lib/python3.5/site-packages/plotoptix/_load_lib.py", line 344, in __init__
    c_rnd = cdll.LoadLibrary(os.path.join(os.path.dirname(__file__), BIN_PATH, "librndSharpOptiX.so"))
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvrtc.so.10.0: cannot open shared object file: No such file or directory
```
it looks like it its looking for the 10.0 version of a file that i have a 10.1 version of (i verfied its presence looking in the cuda directory)

do you have a suggestion for what to do? thank you!

**Comment by robertsulej** [comment]
You are right, it is supposed to work with both, 10.0 and 10.1. But.. librndSharpOptiX.so depends on libnvrtc.so.10.0. I tried to change that to libnvrtc.so, with no success, maybe 10.0 and 10.1 are not binary compatible. Fortunately, making a dedicated library for each CUDA is working fine. I'll push that today together with an updated setup script.

**Comment by robertsulej** [comment]
Ok, pushed changes. If you'd like to give it a try, please, uninstall your current release and setup plotoptix form the repository head.

**Comment by kittles** [comment]
just letting you know i haven't forgotten about this- just dont have time to do a proper run through until maybe tomorrow or the next day (i got some errors that may or may not be related to the actual issue)

**Comment by robertsulej** [comment]
No worries, I also made some progress and can remove dependency on any particular CUDA version at all. Also, CUDA will be required for video encoding only.

**Comment by robertsulej** [comment]
OK, dependencies on CUDA release are removed, new release (0.3.1) is in the repository and in a moment in PyPI. I close this issue. Thanks for the feedback and feel free to complain if anything new appears!

**Comment by kittles** [comment]
i pip installed the latest from github and was able to run in a fresh virtualenv with only the monkey patching of IntEnum as IntFlag. what a thrill! the examples look amazing, and running ray tracing on a gpu after spending the last couple weeks using povray is really exciting. thank you so much for the hard work!

**Comment by robertsulej** [comment]
That's great to hear, thanks!

May I ask what is your Python version? I'd try to reproduce and fix the enum thing.
