### ISSUE TITLE
Misleading documentation for `utils.simplex`

### ISSUE THREAD

**Issue by Artoria2e5** [rnd-team-dev/plotoptix#21]
The summary for `utils.simplex` claims "simplex noise" when it actually makes OpenSimplex noise. The two algorithms are distinct from each other despite the visual similarity of the output.

**Comment by Artoria2e5** [comment]
In related news, the patent on simplex is expect to expire in 9 months. You can probably reduce the code size a lot then!

**Comment by robertsulej** [comment]
Thanks for noting, I'll fix that in a moment!
