### ISSUE TITLE
Customized UI

### ISSUE THREAD

**Issue by ZhiquanW** [rnd-team-dev/plotoptix#27]
Is it possible to add some customized UI (buttons, sliders) into this framework so the user can interact with the object? This can be helpful if the user wants to add/delete objects or change color/size.

**Comment by robertsulej** [comment]
Sure. It just needs time to do it. :)

The plan is to focus on low level features and functionality. But I will try to add something basic in UI as time allows.

**Comment by ZhiquanW** [comment]
Thank you so much!
