### ISSUE TITLE
Error installing examples

### ISSUE THREAD

**Issue by AuSpotter** [rnd-team-dev/plotoptix#28]
In a fresh install of Anaconda, with a fresh env created for plotoptix, there is an error trying to add the examples folder:

`(plotoptix) C:\Users\XXXXX>python -m plotoptix.install examples`
`Traceback (most recent call last):`
`  File "D:\anaconda3\envs\plotoptix\lib\runpy.py", line 188, in _run_module_as_main`
`    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)`
`  File "D:\anaconda3\envs\plotoptix\lib\runpy.py", line 147, in _get_module_details`
`    return _get_module_details(pkg_main_name, error)`
`  File "D:\anaconda3\envs\plotoptix\lib\runpy.py", line 111, in _get_module_details`
`    __import__(pkg_name)`
`  File "D:\anaconda3\envs\plotoptix\lib\site-packages\plotoptix\install\__init__.py", line 16, in <module>`
`    import requests, os`
`ModuleNotFoundError: No module named 'requests'`

The requests library should be added to package requirements I think

**Comment by robertsulej** [comment]
True. Added. Thanks!
