### ISSUE TITLE
Does not work on Ubuntu

### ISSUE THREAD

**Issue by Han-ga86caq** [rnd-team-dev/plotoptix#30]
I installed plotoptix following the instructions in documentation, however, when I tried to run the example in the readme:

```python 
import numpy as np
from plotoptix import TkOptiX

n = 1000000                                  # 1M points, better not try this with matplotlib
xyz = 3 * (np.random.random((n, 3)) - 0.5)   # random 3D positions
r = 0.02 * np.random.random(n) + 0.002       # random radii

plot = TkOptiX()
plot.set_data("my plot", xyz, r=r)
plot.show()
```

And I got the following error message:
```python
********************************************************************************
********************************************************************************
.NET ray tracing libraries initialization failed, cannot continue.
********************************************************************************
********************************************************************************
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.local/lib/python3.10/site-packages/plotoptix/_load_lib.py in __init__(self)
    546         try:
--> 547             json_assembly = clr.System.Reflection.Assembly.LoadFile(json_name)
    548             tiff_assembly = clr.System.Reflection.Assembly.LoadFile(tiff_name)

AttributeError: module 'clr' has no attribute 'System'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-19d747a1c849> in <module>
      1 import numpy as np
----> 2 from plotoptix import TkOptiX
      3 
      4 n = 1000000                                  # 1M points, better not try this with matplotlib
      5 xyz = 3 * (np.random.random((n, 3)) - 0.5)   # random 3D positions

~/.local/lib/python3.10/site-packages/plotoptix/__init__.py in <module>
     22 # import PlotOptiX modules ###############################################
     23 from plotoptix.enums import *
---> 24 from plotoptix.npoptix import NpOptiX
     25 from plotoptix.tkoptix import TkOptiX
     26 

~/.local/lib/python3.10/site-packages/plotoptix/npoptix.py in <module>
     15 from plotoptix.geometry import GeometryMeta
     16 from plotoptix._load_lib import load_optix, PARAM_NONE_CALLBACK, PARAM_INT_CALLBACK
---> 17 from plotoptix.utils import _make_contiguous_vector, _make_contiguous_3d
     18 from plotoptix.enums import *
     19 

~/.local/lib/python3.10/site-packages/plotoptix/utils.py in <module>
     12 from plotoptix.enums import GpuArchitecture, ChannelOrder
     13 
---> 14 _optix = load_optix()
     15 
     16 

~/.local/lib/python3.10/site-packages/plotoptix/_load_lib.py in load_optix()
   1154         optix = _load_optix_win()
   1155     elif PLATFORM == "Linux":
-> 1156         optix = _ClrOptiX()
   1157     else:
   1158         raise NotImplementedError

~/.local/lib/python3.10/site-packages/plotoptix/_load_lib.py in __init__(self)
    552             print(".NET ray tracing libraries initialization failed, cannot continue.")
    553             print(80 * "*"); print(80 * "*")
--> 554             raise ImportError
    555 
    556         clr.AddReference(os.path.splitext(tail)[0])

ImportError: 
```

My system is Ubuntu 22.04, with Nvidia driver version: 510.73.05 and CUDA version 11.6, the required package mentioned in [README.rst](https://github.com/rnd-team-dev/plotoptix#readme). 

According to the message, I checked the corresponding file `_load_lib.py` line 539-554:
```python
        json_name = os.path.join(os.path.dirname(__file__), BIN_PATH, "Newtonsoft.Json.dll")
        tiff_name = os.path.join(os.path.dirname(__file__), BIN_PATH, "BitMiracle.LibTiff.NET.dll")
        rnd_name = os.path.join(os.path.dirname(__file__), BIN_PATH, "RnD.SharpOptiX.dll")

        head, tail = os.path.split(rnd_name)
        sys.path.append(head)

        try:
            json_assembly = clr.System.Reflection.Assembly.LoadFile(json_name)
            tiff_assembly = clr.System.Reflection.Assembly.LoadFile(tiff_name)
            rnd_assembly = clr.System.Reflection.Assembly.LoadFile(rnd_name)
        except:
            print(80 * "*"); print(80 * "*")
            print(".NET ray tracing libraries initialization failed, cannot continue.")
            print(80 * "*"); print(80 * "*")
            raise ImportError
```
It seems that even in Linux, the python code still tries to load .dll files, which is supposed to work only on windows. From my understanding, the equivalence shall be `somthing.so` right? Is it a bug of the code or configuration issue of my system that misleads the code going to this branch? 

Thanks a lot!

**Comment by brennansprinkle** [comment]
Did you ever find a solution to this? Running into a very similar error on my system (Ubuntu 22, python 3.8(tried 3.9 also), Nv Driver 515.65.01, CUDA cuda_11.2.r11.2)

**Comment by brennansprinkle** [comment]
Update: I fixed the issue in the following way
--Part of the problem was that I was using pythonnet 3.0 
--Once I uninstalled pythonnet 3.0 and installed 2.5.2 with
`pip install -U pythonnet==2.5.2 --user`
I would get the following error when importing clr
`mport clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: System.DllNotFoundException: libdl.so assembly:<unknown assembly> type:<unknown type> member:(null)
`
--This was fixed with a symbolic link
`sudo ln -s /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so`
and then everything worked

Hope this helps folks with a similar issue

**Comment by robertsulej** [comment]
Hi, thanks for the feedback.
I did not test pythonnet 3.0 yet - I tried with one of the beta releases and there were still clashes with various mono/python/ubuntu combinations, thats why I left recommendation for pythonnet 2.5.2 ans python 3.8 in the release notes.

Now I'll try again setting up everything with the pythonnet 3.0. I'll post updates here.

**Comment by robertsulej** [comment]
OK, updated code works with pythonnet 3.0. I tested it on python 3.8 and 3.10 - all looks good, but if you find problems, please, let me know. Code is now on the [branch](https://github.com/rnd-team-dev/plotoptix/tree/r0.14.4), I'll freeze the release and post it on PyPI soon.

Don't know how I missed the original post of this issue... Just to clarify: loading dll in Linux is correct, these dll's are .net stuff and contain code that is used by both, Linux and Windows .net frameworks.

**Comment by brennansprinkle** [comment]
Wonderful! Thank you! I'll try the new pull soon and report back!

**Comment by robertsulej** [comment]
Release 0.14.4 is now on PyPI, closing the issue, but feel free to re-open in caso of problems.
