### ISSUE TITLE
Moon Example

### ISSUE THREAD

**Issue by Carandiru0** [rnd-team-dev/plotoptix#35]
Is the moon example working? Does it run locally or only in a notebook?
Thanks!

**Comment by robertsulej** [comment]
It should run locally in a notebook. I did not try it after last code updates though. I'll check and let you know later today.

**Comment by robertsulej** [comment]
Just tried in Windows and seems OK. Please, let me know some more details what problems it makes for you.

**Comment by robertsulej** [comment]
OK, closing for the moment. Feel free to reopen in case of problems with the example.
