### ISSUE TITLE
Synchronization with PlotOptiX

### ISSUE THREAD

**Issue by vitalitylearning2021** [rnd-team-dev/plotoptix#36]
### Code #1 - Synchronization with the ```threading``` library

I have the following code.

```
import  numpy               as      np
from    plotoptix           import  NpOptiX
import  matplotlib.pyplot   as      plt
import  threading

class params:
    done = threading.Event()

verticesTriangles   = np.array([[-1, -1, 0], [1, -1, 0], [-1, 1, 0], [1, -1, 0], [1, 1, 0], [-1, 1, 0]])
faceTriangles       = np.array([[0, 1, 2], [3, 4, 5]])

rt                  = NpOptiX(width = 20, height = 20)

rt.set_mesh("Mesh", verticesTriangles, faceTriangles)

rt.setup_camera("Cam", eye = [0, 0, 2], fov = 25)

rt.start()

# --- https://superfastpython.com/thread-event-object-in-python/
if params.done.wait(3):
    print("Waiting for event to be set.-.")
else:
    print("Event set. Continue.")
    
hitPositionsData = rt._hit_pos
xHitPositions = hitPositionsData[:, :, 0]
yHitPositions = hitPositionsData[:, :, 1]
zHitPositions = hitPositionsData[:, :, 2]
dHitPositions = hitPositionsData[:, :, 3]

hitTriangle   = rt._geo_id[:, :, 1].reshape(rt._height, rt._width)
    
print("Shape of rays array is {}.".format(xHitPositions.shape))

xHitPositions = xHitPositions[hitTriangle < 0xFFFFFFFF]
yHitPositions = yHitPositions[hitTriangle < 0xFFFFFFFF]

print("Shape of hitting rays array is {}.".format(xHitPositions.shape))

plt.plot(xHitPositions, yHitPositions, 'bo')
plt.show()

plt.imshow(dHitPositions)
plt.colorbar()
plt.show()

rt.close()
```

The code works correctly. The ```threading``` library is used to wait ```3``` seconds for the device to complete and then move the results of the computation to the host. 

### Code #2 - Synchronization with ```on_launch_finished```

I have modified the above code to enforce synchronization with ```on_launch_finished```.

```
import  numpy               as      np
from    plotoptix           import  NpOptiX
import  matplotlib.pyplot   as      plt
import  threading

class params:
    done = threading.Event()

def wait_for_gpu(rt: NpOptiX) -> None:
    print("gpu done")
    params.done.set()

verticesTriangles   = np.array([[-1, -1, 0], [1, -1, 0], [-1, 1, 0], [1, -1, 0], [1, 1, 0], [-1, 1, 0]])
faceTriangles       = np.array([[0, 1, 2], [3, 4, 5]])

rt                  = NpOptiX(on_launch_finished = wait_for_gpu, width = 20, height = 20)

rt.set_mesh("Mesh", verticesTriangles, faceTriangles)

rt.setup_camera("Cam", eye = [0, 0, 2], fov = 25)

rt.start()
    
hitPositionsData = rt._hit_pos
xHitPositions = hitPositionsData[:, :, 0]
yHitPositions = hitPositionsData[:, :, 1]
zHitPositions = hitPositionsData[:, :, 2]
dHitPositions = hitPositionsData[:, :, 3]

hitTriangle   = rt._geo_id[:, :, 1].reshape(rt._height, rt._width)
    
print("Shape of rays array is {}.".format(xHitPositions.shape))

xHitPositions = xHitPositions[hitTriangle < 0xFFFFFFFF]
yHitPositions = yHitPositions[hitTriangle < 0xFFFFFFFF]

print("Shape of hitting rays array is {}.".format(xHitPositions.shape))

plt.plot(xHitPositions, yHitPositions, 'bo')
plt.show()

plt.imshow(dHitPositions)
plt.colorbar()
plt.show()

rt.close()
```

The code is not working.

### Code #3 - Synchronization with the ```threading``` library and with ```on_launch_finished```

In this last code, I'm using both, the ```threading``` library and the ```on_launch_finished```.

```
import  numpy               as      np
from    plotoptix           import  NpOptiX
import  matplotlib.pyplot   as      plt
import  threading

class params:
    done = threading.Event()

def wait_for_gpu(rt: NpOptiX) -> None:
    print("gpu done")
    params.done.set()

verticesTriangles   = np.array([[-1, -1, 0], [1, -1, 0], [-1, 1, 0], [1, -1, 0], [1, 1, 0], [-1, 1, 0]])
faceTriangles       = np.array([[0, 1, 2], [3, 4, 5]])

rt                  = NpOptiX(on_launch_finished = wait_for_gpu, width = 20, height = 20)

rt.set_mesh("Mesh", verticesTriangles, faceTriangles)

rt.setup_camera("Cam", eye = [0, 0, 2], fov = 25)

rt.start()

# --- https://superfastpython.com/thread-event-object-in-python/
if params.done.wait(3):
    print("Waiting for event to be set.-.")
else:
    print("Event set. Continue.")
    
hitPositionsData = rt._hit_pos
xHitPositions = hitPositionsData[:, :, 0]
yHitPositions = hitPositionsData[:, :, 1]
zHitPositions = hitPositionsData[:, :, 2]
dHitPositions = hitPositionsData[:, :, 3]

hitTriangle   = rt._geo_id[:, :, 1].reshape(rt._height, rt._width)
    
print("Shape of rays array is {}.".format(xHitPositions.shape))

xHitPositions = xHitPositions[hitTriangle < 0xFFFFFFFF]
yHitPositions = yHitPositions[hitTriangle < 0xFFFFFFFF]

print("Shape of hitting rays array is {}.".format(xHitPositions.shape))

plt.plot(xHitPositions, yHitPositions, 'bo')
plt.show()

plt.imshow(dHitPositions)
plt.colorbar()
plt.show()

rt.close()
```

Surprisingly, the code is again not working.

### Question - Could you explain such a behavior?

Thank you for any help.

**Comment by robertsulej** [comment]
Hi,

Everything is fine.

Code #1 is waiting 3 seconds, but the event is not set so waiting times out. 3 seconds is enough to calculate everything that is why you get results.

Code #2 is not waiting so it is trying to read results too quickly.

Code #3 is waiting for the first accumulaton launch (out of default 4) and you read when 3 other launches are still overwriting data. Please, try `on_rt_accum_done` instead of `on_launch_finished` or set the number of accumulation frames to 1 before starting:

```
rt.set_param(max_accumulation_frames=1)
rt.start()
```

In your case the most correct will be to use both above changes (accumulation is needed when launches are doing randomized calculations, but for distance checking everythin is deterministic).

**Comment by vitalitylearning2021** [comment]
Thank you very much for your answer. I have modified code #3. In particular:

1. I have changed `on_launch_finished` to `on_rt_completed`;
2. I have added

`rt.set_param(max_accumulation_frames = 1)`

as suggested. 

I noticed that, with these changes, the bahavior of the code keeps unaltered: the ray launch seems not randomized. However, if I set

`rt.set_param(max_accumulation_frames = 2)`,

randomization occurs. Is there an explanation for that?

**Comment by robertsulej** [comment]
Ah, OK, right. In the first frame rays are launched always in the center of pixels, then next launches have random jitter of the ray direction within the pixel size. This depends also on the camera mode. Another thing to note is that default material is diffuse - rays will scatter of the surface and continue which you may not need. You can use [flat](http://plotoptix.rnd.team/materials.html#plotoptix.materials.m_flat) material for your mesh to minimize calculations.

```
from modules.materials import m_flat
...
rt.setup_material("flat", m_flat)
...
rt.set_mesh("Mesh", verticesTriangles, faceTriangles, mat="flat")
```

It is also possible to limit [number of ray segments](http://plotoptix.rnd.team/npoptix_config.html#raytracer-configuration) that are traced:
```
rt.set_uint("path_seg_range", 1, 1)
```

Let me know what is your goal, maybe I can suggest something more.

**Comment by vitalitylearning2021** [comment]
Thank you for your answer, again.

I'm interested in understanding how does PlotOptiX work as I would like to set up an acoustic ray tracer, for fun. Using PlotOptiX would avoid me hardcoding directly in OptiX.

To this end, I would need to collect the results of ray tracing, namely, intersection points, reflected and refracted rays. Therefore, I would need to understand PlotOptiX synchronization.

For the time being, I'm considering the simple case of collecting reflection points and distances only as I'm dealing with a plate. 

Unfortunately, synchronization is still unclear to me, of course due to my poor understanding of synchronization issues in general.

Starting from the beginning, I understand that using

`on_rt_accum_done = wait_for_gpu`

or similars (`on_launch_finished`, `on_rt_completed`, etc.) triggers to execute the `wait_for_gpu` function after completion.

However, if I use the simple code:

```
import  numpy               as      np
from    plotoptix           import  NpOptiX
import  matplotlib.pyplot   as      plt
import  threading

class params:
    done = threading.Event()

def wait_for_gpu(rt: NpOptiX) -> None:
    print("Task completed")
    params.done.set()

verticesTriangles   = np.array([[-1, -1, 0], [1, -1, 0], [-1, 1, 0], [1, -1, 0], [1, 1, 0], [-1, 1, 0]])
faceTriangles       = np.array([[0, 1, 2], [3, 4, 5]])

rt                  = NpOptiX(on_rt_accum_done = wait_for_gpu, width = 20, height = 20)

rt.set_mesh("Mesh", verticesTriangles, faceTriangles)

rt.setup_camera("Cam", eye = [0, 0, 2], fov = 25)

rt.set_param(max_accumulation_frames = 5)
rt.start()

rt.close()
```

the `Task completed` message does not show up. Opposite to that, if I skip `rt.close()`, it does.

Moreover, in general, I would like to avoid synchronizations like:

```
if params.done.wait(10):
    print("Waiting for event to be set.-.")
else:
    print("Event set. Continue.")
```

which wait for a manually fixed number of seconds as I do not know how much time do the computations need for completing.

I would like a way to wait for the whole ray tracing to be completed and, after that, triggering the CPU to collect the results (intersection points and distances for the simple example I'm dealing with).

**Comment by robertsulej** [comment]
OK. I was already helping with a similar application (a radio wave propagation). Probably I should work on some reasonale api to support this pattern, as going straight to Optix is indeed a bit painful.  Nex days I'll write you a summary on how things are flowing in plotoptix. Basically collecting interesting results should happen in callbacks. Waiting on the threading event is only a the most simple code I found to demonstrate that sync is needed to read results from the raytracer (I get many questions "why there are all zeros in the output").

**Comment by vitalitylearning2021** [comment]
Thank you very much for your help. A PlotOptiX working summary would be great.

**Comment by robertsulej** [comment]
Hi, I added [this section](https://plotoptix.rnd.team/npoptix.html#ray-tracing-and-compute-loop) in the docs. Hope it can explain somewhat the workflow. Please, have a look also at the sample notebook linked there.

When I was working on the mobile field coverage studies, there was an effect of the refraction on the geometry edges. This may be also the case in sound wave propagation. To implement this we tried to add a wireframe to the mesh, where wireframe had a specialized closest-hit program. I think the problem may be approached also with the rounded mesh edges - but it's just a guess, to be checked if you'd like.

**Comment by vitalitylearning2021** [comment]
Thank you very much for the improved documentation. It really helped a lot.
