### ISSUE TITLE
Running on Google Colab

### ISSUE THREAD

**Issue by will-holley** [rnd-team-dev/plotoptix#5]
Hello - I am excited to try out your library on a Google Colaboratory Notebook. However, I am running into difficultly setting it up, having tried both the Linux and GCP instructions.  Has this been attempted by yourself or others, and if so is it possible?  Thanks!

```bash
**********************************************************************************
**********************************************************************************
Video encoding library initialization failed, encoding features are not available.
**********************************************************************************
**********************************************************************************
[ERROR] (MainThread) Initial setup failed, see errors above.
[ERROR] (MainThread) Geometry setup failed.
[ERROR] (MainThread) Camera setup failed.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/plotoptix/npoptix.py", line 219, in run
    assert self._is_scene_created, "Scene is not ready, see initialization messages."
AssertionError: Scene is not ready, see initialization messages.

[ERROR] (MainThread) Raytracing output startup timed out.
```

**Comment by robertsulej** [comment]
Hi Will,

Yes, I tried Colab. They have too old drivers installed, please see this issue: https://github.com/googlecolab/colabtools/issues/620

I was able to properly install all the prerequisites, so we are just waiting for the driver update. It could be a perfect environment for sharing PlotOptiX.

**Comment by robertsulej** [comment]
Oh, wait a second! I just checked again:

Wed Sep  4 08:41:42 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+

That one should work, I'll try it now.

**Comment by robertsulej** [comment]
Ok, it seems that the problem is with the OptiX library. I am discussing this issue [here](https://devtalk.nvidia.com/default/topic/1062573/optix/optix-6-ptx-parse-error-internal-error-while-parsing-builtin-declarations/?offset=3#5380687). If there is a workaround I'll fix it with the next release. If not, we'll have to wait again for the driver update in Google Colab and I'll also switch to updated OptiX libraries.

**Comment by will-holley** [comment]
Hi Robert - Thanks for the expedient and extensive follow up!

**Comment by boulos** [comment]
Btw, Colab just updated to 11.2, and I made an end-to-end example:

 https://github.com/googlecolab/colabtools/issues/620#issuecomment-792170689

A lot of the set vs update stuff ends up being fairly annoying in the colab setting (an "update or set" would be nice, or just have things like ```set_data``` work even if a previous value exists).

Thanks for plotoptix!

**Comment by robertsulej** [comment]
Yup, set/update defenitively to be changed. I'll improve on that as soon as I finish current project.

**Comment by robertsulej** [comment]
I came back to check if/how Colab is working. They still don't have the recent drivers, but with a compatible plotoptix release everything seems ok. Here is the [working notebook](https://colab.research.google.com/drive/1RSVKYSZl1NjfttBwyuoehaEkNWnXwy6t?usp=sharing). I'll check from time to time and maintain it up to date.
