### ISSUE TITLE
issue on running a python script

### ISSUE THREAD

**Issue by Nasrollah** [rnd-team-dev/plotoptix#52]
Dear plotoptix developers,

I have installed plotoptix in a cluster to visualize some results. I have a python script to do this. When I tried to run plotoptix using this command “python3 ”, I got this error:
“
(SlenderBody) [scnhv@login1.arc4 plots]$ python3 BundledFibers.py 240
**********************************************************************************
**********************************************************************************
Video encoding library initialization failed, encoding features are not available.
**********************************************************************************
**********************************************************************************
********************************************************************************
********************************************************************************
Low level ray tracing libraries initialization failed, cannot continue.
********************************************************************************
********************************************************************************
Traceback (most recent call last):
  File "/home/home01/scnhv/.conda/envs/SlenderBody/lib/python3.11/site-packages/plotoptix/_load_lib.py", line 1208, in __init__
    c_rnd = cdll.LoadLibrary(os.path.join(os.path.dirname(__file__), BIN_PATH, "librndSharpOptiX7.so"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/home01/scnhv/.conda/envs/SlenderBody/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/home01/scnhv/.conda/envs/SlenderBody/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/home01/scnhv/SlenderBody/Python/plots/BundledFibers.py", line 15, in <module>
    from plotoptix import TkOptiX
  File "/home/home01/scnhv/.conda/envs/SlenderBody/lib/python3.11/site-packages/plotoptix/__init__.py", line 24, in <module>
    from plotoptix.npoptix import NpOptiX
  File "/home/home01/scnhv/.conda/envs/SlenderBody/lib/python3.11/site-packages/plotoptix/npoptix.py", line 17, in <module>
    from plotoptix.utils import _make_contiguous_vector, _make_contiguous_3d
  File "/home/home01/scnhv/.conda/envs/SlenderBody/lib/python3.11/site-packages/plotoptix/utils.py", line 14, in <module>
    _optix = load_optix()
             ^^^^^^^^^^^^
  File "/home/home01/scnhv/.conda/envs/SlenderBody/lib/python3.11/site-packages/plotoptix/_load_lib.py", line 2007, in load_optix
    optix = _ClrOptiX_v3()
            ^^^^^^^^^^^^^^
  File "/home/home01/scnhv/.conda/envs/SlenderBody/lib/python3.11/site-packages/plotoptix/_load_lib.py", line 1213, in __init__
    raise ImportError
ImportError
(SlenderBody) [scnhv@login1.arc4 plots]$

“
I would be wondering if you could kindly guide me on this issue.

Best regards,
Nasrollah Hajaliakbari

**Comment by robertsulej** [comment]
That looks like a problem with the NVIDIA driver installation. Please, make sure you have it available in your cluster nodes, you can verify this running `nvidia-smi` command.

In case you are using docker, [here](https://github.com/rnd-team-dev/plotoptix/issues/46#issuecomment-1555329784) are hints how to deal with its issues.

**Comment by Nasrollah** [comment]
Dear Mr. Robert Sulej

Thanks for your response. I fix that problem and now I have a new problem for which I attached a logfile for that. I do not know what it is.

I would be wondering if you could kindly provide a solution for that.

Kind regards,
Nasrollah Hajaliakbari 

[logsoptix1.txt](https://github.com/rnd-team-dev/plotoptix/files/12507359/logsoptix1.txt)

**Comment by robertsulej** [comment]
One step forward - GPU is there. :)
But you are still stopped on the initialization. V100 should work, so likely the problem is still the configuration. Could you, please, post the output from `nvidia-smi` command? We'll see which driver is installed (note, all requirements are also in the [readme](https://github.com/rnd-team-dev/plotoptix#system-requirements)).

**Comment by Nasrollah** [comment]
Dear Mr. Robert Sulej,

Thanks for your response.
Based on your request I attached a log file related to that,

Best regards,
Nasrollah Hajaliakbari
[nvidia-smi.log](https://github.com/rnd-team-dev/plotoptix/files/12511910/nvidia-smi.log)

**Comment by robertsulej** [comment]
OK, driver release is correct.

Looking at your original post I can see you are trying to run a script `BundledFibers.py`. I searched for it and found it could be [this one sample](https://github.com/stochasticHydroTools/SlenderBody/blob/master/Python/plots/BundledFibers.py) from the SlenderBody repository. This scriptis is using interactive rendering, `TkOptiX`, which might be problematic to run remotely. Probably you'll need to adopt `NpOptiX`, which can run without GUI window.

But first let's try making it working at all. Could you, please, try [this script](https://github.com/rnd-team-dev/plotoptix/blob/master/examples/2_animations_and_callbacks/0_wait_for_raytracing_done.py) from examples? It creates a simple scene and does not rely on any other data. You can simply copy it to the cluster  node and run.

If it crashes in the same way as your script, please, try selecting specific devive - maybe something is limiting your access to all devices on the node. Try adding `device` parameter to the constructor [here](https://github.com/rnd-team-dev/plotoptix/blob/master/examples/2_animations_and_callbacks/0_wait_for_raytracing_done.py#L25) and select GPU 0 or 1:

```
rt = NpOptiX(on_rt_accum_done=accum_done, width=800, height=500, devices=[0])
```
or
```
rt = NpOptiX(on_rt_accum_done=accum_done, width=800, height=500, devices=[1])
```

**Comment by Nasrollah** [comment]
Dear Mr. Robert Sulej,

Thanks for your response.

You are right that I am using that script for visualization.
Based on your request, I firstly run the script without detemining the device and I got the same error.
After that, I tried to add device and I got this error , attached here again.

I would be wondering if you could kindly guide me on this issue.

Best regards,
Nasrollah Hajaliakbari
[logsoptix2.txt](https://github.com/rnd-team-dev/plotoptix/files/12512400/logsoptix2.txt)

**Comment by robertsulej** [comment]
The error in the attached output is:
```
python3: can't open file '/home/home01/scnhv/SlenderBody/Python/plots/0_wait_for_raytracing_done.py\r': [Errno 2] No such file or directory
```
so something went wrong before running the script.

Might be easier if you could log into the cluster node in the interactive mode.

**Comment by Nasrollah** [comment]
Dear Mr. Robert Sulej

Thanks for your reponse.  Based on your comment, I used a sh file to do that. I would be wondering if you could guide me about that.
[JobTest.txt](https://github.com/rnd-team-dev/plotoptix/files/12512884/JobTest.txt)
[logsoptix2.txt](https://github.com/rnd-team-dev/plotoptix/files/12512885/logsoptix2.txt)


Best regards,
Nasrollah Hajaliakbari
