### ISSUE TITLE
COMPILE ERROR: Malformed input

### ISSUE THREAD

**Issue by bbored** [rnd-team-dev/plotoptix#56]
Is version 0.17.1 Maxwell (sm_50) compatible (940MX)?
On linux env I got the following:

`Video encoding library initialization failed, encoding features are not available.`

`CUDA error on synchronize with error 'no kernel image is available for execution on the device'`

`[ 2][    COMPILER]: COMPILE ERROR: Malformed input. See compile details for more information.`
`Warning: Requested debug level "OPTIX_COMPILE_DEBUG_LEVEL_MINIMAL", but input module does not include any debug information.`
`Error: Invalid target architecture. Maximum feasible for current context: sm_50, found: sm_60`

`OPTIX_ERROR_INVALID_INPUT: Optix call optixModuleCreate( m_context, &m_module_compile_options, m_pipeline_compile_options, ptx.data(), ptx.size(), log, &sizeof_log, &mnew )failed: Modules.cpp:49)`

On Windows with a 920MX (sm_52) same error
Thanks

**Comment by robertsulej** [comment]
Hi, I'll check and let you know, need some hours to be back online.

**Comment by robertsulej** [comment]
All kernels were compiled for sm_60. I must have bumped this for feature tests and did not bring down. Everything seems to work fine with sm_50 though. The fix compiled for sm_50 is in [this branch](https://github.com/rnd-team-dev/plotoptix/tree/fix_sm_num). Please, try code from the branch before the next release is ready.

**Comment by bbored** [comment]
@robertsulej Thanks a lot! It works with warning:

`Video encoding library initialization failed, encoding features are not available.`

Tested  example: 0_try_plotoptix.py

**Comment by robertsulej** [comment]
That's great. The warning appears in linux if you have no ffmpeg installed. It should be gone when you install it (ffmpeg in [prerequisites](https://github.com/rnd-team-dev/plotoptix#linux-prerequisites)).
