### ISSUE TITLE
Interaction in visualisation (tk?) and ffmpeg

### ISSUE THREAD

**Issue by davidcortesortuno** [rnd-team-dev/plotoptix#60]
Hi, I successfully ran some of the examples, however, the tk window does not let me zoom or interact with the visualisations in any way, except for the single mouse click to rotate the image. I installed tk via pip, is that the right way?

I also installed ffmpeg 7, but I keep getting the error `Video encoding library initialization failed, encoding features are not available.` . I'm using the latest dev branch.

**Comment by robertsulej** [comment]
I had a chance to look at ffmpeg problem in Linux. It should be fixed now in the branch [r0.18.2](https://github.com/rnd-team-dev/plotoptix/tree/r0.18.2). In case it reappears, please let me know (ffmpeg can bump the library version without changing the ffmper release number...).

[Here](https://github.com/rnd-team-dev/plotoptix/tree/master/examples) are the keys to use with tk visualization. Are these not working properly? tk via pip is OK, if the tk window opens then all commands should work.

**Comment by robertsulej** [comment]
Updates are now in master and the new release 0.18.2 is available on PyPI. Feel free to reopen in case of problems!
