### ISSUE TITLE
About loading "denoiser"

### ISSUE THREAD

**Issue by wzpy** [rnd-team-dev/plotoptix#8]
Dear author, I have nearly installed and can use plotoptimx, but when I do "Python - M plotoptimx. Install denoiser", it will display "downloading failed. Package not installed." do you know why?

**Comment by robertsulej** [comment]
I have just verified the installation and it works correctly.
Denoiser file is quite large, please try installing again. The only option to see this error message is a network connection problem.

**Comment by robertsulej** [comment]
Closing the issue, but feel free to reopen in case of further questions. Merry Christmas!
